class Commands:
    LEECH = "leech@pyrorobot"
    PURGE = "purge"
    PAUSEALL = "pauseall"
    RESUMEALL = "resumeall"
    STATUS = "status@pyrorobot"
    SETTINGS = "settings@pyrorobot"
    EXEC = "exec"
    UPLOAD = "upload"
    YTDL = "ytdl@pyrorobot"
    PYTDL = "pytdl@pyrorobot"
    ABOUT = "about"
    GETLOGS = "getlogs"
    SERVER = "server"
    USERSETTINGS = "usetting@pyrorobot"
    INSTADL = "instadl"
